import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const media = '/media/';

const projects = [
  { id:'barista', type:'interactive', label:'تجربة تفاعلية', title:'كن باريستا', subtitle:'تجربة تدريبية للقهوة والموهيتو', desc:'تجربة متسلسلة تحاكي وردية باريستا: استلام الطلبات، اختيار المكونات، تحضير المشروب، فن اللاتيه، ثم موقف خدمة حقيقي.', meta:'مؤسسة التدريب المهني · إعداد وفكرة: تمارا الشباطات', src:'barista.html', accent:'coral', icon:'☕' },
  { id:'computer', type:'interactive', label:'تجربة تفاعلية', title:'Computer from 1999', subtitle:'حاسوب من عام 1999', desc:'تجربة نوستالجية تعيد واجهة Windows 98 إلى الحياة مع ملفات وألعاب وتفاصيل صغيرة قابلة للاستكشاف.', meta:'تجربة تفاعلية · Tamara’s Portfolio', src:'computer-1999.html', accent:'lime', icon:'▣' },
  { id:'ohm', type:'interactive', label:'مختبر تعليمي', title:'مختبر قانون أوم', subtitle:'الكهرباء بطريقة مرئية', desc:'مختبر تفاعلي يشرح العلاقة بين الجهد والمقاومة وشدة التيار عبر دائرة كهربائية حيّة ولوحة تحكم بالمتغيرات.', meta:'مختبر الفيزياء الكهربائية التفاعلي', src:'ohm-lab.html', accent:'blue', icon:'⚡' },
  { id:'maze', type:'interactive', label:'لعبة تفاعلية', title:'Maze Runner', subtitle:'5 مراحل من الحماس', desc:'لعبة متاهة بخمس مراحل، عملات، وحوش، بوابة خروج، مؤقت، أرواح ونظام نقاط.', meta:'5 مراحل · Collect · Avoid · Escape', src:'maze-runner.html', accent:'violet', icon:'🌀' },
  { id:'safety', type:'video', label:'فيديو معدّل', title:'Child Safety Monitor', subtitle:'قصة قصيرة عن الطمأنينة', desc:'سلسلة فيديوهات معدّلة تبدأ بالتشويق وتنتهي بلحظة راحة أم بعد اكتشاف جهاز مراقبة الطفل.', meta:'فيديوهات معدّلة من حقيبة الأعمال', poster:'child-safety-teaser.jpg', video:'child-safety-teaser.mp4', accent:'coral', icon:'◉' },
  { id:'aqaba', type:'visual', label:'صورة مولدة بالـ AI', title:'Aqaba 2050', subtitle:'زوار العقبة يستكشفون البحر', desc:'مشهد بصري مستقبلي مستوحى من العقبة والبحر، ضمن مجموعة الصور المولدة بالذكاء الاصطناعي.', meta:'صور مولدة بالذكاء الاصطناعي', poster:'aqaba-visitors-web.jpg', accent:'blue', icon:'✦' },
  { id:'digital', type:'visual', label:'مهارات رقمية', title:'Digital tools', subtitle:'أدوات رقمية للمهام اليومية', desc:'مادة بصرية ضمن مسار تعلم المهارات الرقمية، تعرض أدوات رقمية للمهام اليومية في المنطقة.', meta:'تعلم مهارات رقمية', poster:'digital-tools-web.jpg', accent:'lime', icon:'✺' },
  { id:'anatomy', type:'education', label:'محتوى تعليمي', title:'Human Anatomy', subtitle:'رحلة بصرية عبر جسم الإنسان', desc:'عرض تعليمي بصري من 14 شريحة، من الخلية الواحدة إلى الأجهزة المتكاملة التي تبقي الإنسان على قيد الحياة.', meta:'إعداد: قسم التشريح الطبي · 2026', poster:'tamara-aqaba-web.jpg', accent:'violet', icon:'◌' },
];

const skills = ['تصميم تجارب تفاعلية','المحتوى التعليمي البصري','تحرير الفيديو','الصور المولّدة بالذكاء الاصطناعي','التجارب القصصية','التصميم الرقمي'];
const nav = [['about','عن تمارا'],['skills','المهارات'],['projects','المشاريع'],['experience','الخبرة'],['creative','أعمال إبداعية'],['contact','تواصل']];

function Arrow(){ return <span className="arrow" aria-hidden="true">↗</span> }
function SectionKicker({children, n}){ return <div className="section-kicker"><span>{n}</span><i></i><b>{children}</b></div> }

function App(){
 const [menu,setMenu]=useState(false); const [filter,setFilter]=useState('all'); const [active,setActive]=useState(null);
 const filtered=useMemo(()=>filter==='all'?projects:projects.filter(p=>p.type===filter),[filter]);
 useEffect(()=>{document.body.style.overflow=active?'hidden':''; return()=>document.body.style.overflow=''},[active]);
 const go=(id)=>{setMenu(false); document.getElementById(id)?.scrollIntoView({behavior:'smooth'});};
 return <>
  <header className="topbar"><a className="brand" href="#top" onClick={()=>go('top')}><span className="brand-mark">ت</span><span>تمارا<small>حقيبة أعمال رقمية</small></span></a>
   <nav className={menu?'nav open':'nav'}>{nav.map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setMenu(false)}>لنصنع شيئًا ↗</a></nav>
   <button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="فتح القائمة">{menu?'×':'☰'}</button>
  </header>
  <main id="top">
   <section className="hero shell">
    <div className="hero-copy"><div className="eyebrow"><span className="pulse"></span> متاحة لمشروع إبداعي جديد</div><h1>أحوّل الأفكار<br/><em>إلى تجارب</em><br/>تُعاش.</h1><p className="hero-lead">تمارا الشباطات — أصمم تجارب رقمية، محتوى تعليمي، وصورًا وفيديوهات تحمل فكرة واضحة وتترك أثرًا.</p><div className="hero-actions"><a className="button primary" href="#projects">استكشف الأعمال <Arrow/></a><a className="text-link" href="#about">من أنا؟ <Arrow/></a></div></div>
    <div className="hero-art"><div className="orb orb-one"></div><div className="orb orb-two"></div><div className="hero-image-wrap"><img src={media+'tamara-aqaba-web.jpg'} alt="عمل بصري من حقيبة أعمال تمارا" fetchPriority="high"/><div className="image-label"><span>01 / 08</span><b>أفكار تتحرك</b></div></div><div className="stamp">DIGITAL<br/>STORIES<br/><span>✦</span></div></div>
    <div className="scroll-cue"><span>اسحب للاستكشاف</span><i></i></div>
   </section>
   <section id="about" className="about shell"><SectionKicker n="01">عن تمارا</SectionKicker><div className="about-grid"><h2>حين تصبح التقنية<br/><span>مساحة للخيال.</span></h2><div><p className="large-copy">أبني أعمالًا تجمع بين الفكرة، الصورة، والتفاعل. في حقيبتي تجارب تعليمية وألعاب ومختبرات رقمية، إلى جانب فيديوهات وصور مولّدة بالذكاء الاصطناعي.</p><p className="muted">من تجربة «كن باريستا» التدريبية إلى مختبر قانون أوم ومتاهة بخمس مراحل — كل مشروع يبدأ بسؤال: كيف نجعل المعرفة أو القصة أكثر قابلية للّمس؟</p><a className="text-link" href="#projects">شاهد طريقة التفكير <Arrow/></a></div></div></section>
   <section id="skills" className="skills shell"><SectionKicker n="02">ما أفعله</SectionKicker><div className="skills-grid"><h2>مساحات<br/><em>أتحرك بينها.</em></h2><div className="skill-list">{skills.map((s,i)=><div className="skill" key={s}><span>0{i+1}</span><b>{s}</b><Arrow/></div>)}</div></div></section>
   <section id="projects" className="projects shell"><div className="projects-head"><div><SectionKicker n="03">المشاريع المختارة</SectionKicker><h2>أعمال حقيقية،<br/><em>تجارب قابلة للّمس.</em></h2></div><p>مجموعة من التجارب الرقمية، الأعمال البصرية، والمحتوى التعليمي المستخرج من حقيبة أعمال تمارا.</p></div><div className="filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>الكل <sup>{projects.length}</sup></button><button className={filter==='interactive'?'active':''} onClick={()=>setFilter('interactive')}>تفاعلي <sup>4</sup></button><button className={filter==='video'?'active':''} onClick={()=>setFilter('video')}>فيديو <sup>1</sup></button><button className={filter==='visual'?'active':''} onClick={()=>setFilter('visual')}>بصري <sup>2</sup></button><button className={filter==='education'?'active':''} onClick={()=>setFilter('education')}>تعليمي <sup>1</sup></button></div><div className="project-grid">{filtered.map((p,i)=><ProjectCard key={p.id} p={p} i={i} onOpen={()=>setActive(p)}/>)}</div></section>
   <section id="experience" className="experience shell"><SectionKicker n="04">الخبرة كما تظهر في الأعمال</SectionKicker><div className="timeline"><div className="timeline-item"><span className="year">01</span><div><h3>مؤسسة التدريب المهني</h3><p>برنامج التدريب الفندقي — تجربة «كن باريستا» التفاعلية، إعداد وفكرة: تمارا الشباطات.</p></div><b>تجربة رقمية</b></div><div className="timeline-item"><span className="year">02</span><div><h3>التعلم الرقمي</h3><p>مسار «تعلم مهارات رقمية» مع مادة بصرية عن الأدوات الرقمية والمهام اليومية.</p></div><b>محتوى بصري</b></div><div className="timeline-item"><span className="year">03</span><div><h3>التعليم والتجريب</h3><p>مختبر قانون أوم، عرض علم التشريح البشري، وتجارب تفاعلية تجعل المعلومة قابلة للاستكشاف.</p></div><b>تعليم تفاعلي</b></div></div></section>
   <section id="creative" className="creative shell"><div className="creative-banner"><div><SectionKicker n="05">مساحة إبداعية</SectionKicker><h2>الصورة، الصوت،<br/><em>والحركة.</em></h2><p>صور مولدة بالذكاء الاصطناعي، مسارات صوتية، وفيديوهات معدلة — طبقات مختلفة لصناعة عالم بصري متكامل.</p></div><div className="creative-mosaic"><img src={media+'facebook-ad-web.jpg'} alt="تصميم إعلان بصري" loading="lazy"/><img src={media+'cards-web.jpg'} alt="بطاقات مولدة" loading="lazy"/><img src={media+'aqaba-visitors-web.jpg'} alt="مشهد من العقبة" loading="lazy"/></div></div></section>
   <section id="contact" className="contact shell"><SectionKicker n="06">لنبقى على تواصل</SectionKicker><div className="contact-inner"><h2>لديك فكرة؟<br/><em>لنعطها شكلًا.</em></h2><a className="contact-email" href="https://github.com/tamara126enad/Tamara-Portfolio" target="_blank" rel="noreferrer">افتحي المستودع على GitHub <Arrow/></a><div className="contact-foot"><span>حقيبة أعمال تمارا · 2026</span><span>صُنع بشغف وفضول</span></div></div></section>
  </main><footer><span>© 2026 تمارا الشباطات</span><a href="#top">إلى الأعلى ↑</a></footer>
  {active&&<ProjectModal p={active} onClose={()=>setActive(null)}/>} 
 </>
}
function ProjectCard({p,i,onOpen}){return <article className={'project-card '+p.accent} style={{'--delay':`${i*60}ms`}} onClick={onOpen} tabIndex="0" onKeyDown={e=>e.key==='Enter'&&onOpen()}><div className="card-media">{p.poster?<img src={media+p.poster} alt={p.title} loading="lazy"/>:<div className="abstract"><span>{p.icon}</span><small>INTERACTIVE<br/>EXPERIENCE</small></div>}<div className="card-shade"></div><span className="card-open">↗</span>{p.type==='interactive'&&<span className="live-dot">تجربة حيّة</span>}</div><div className="card-body"><div><span className="card-label">{p.label}</span><h3>{p.title}</h3><p>{p.subtitle}</p></div><span className="card-no">0{i+1}</span></div></article>}
function ProjectModal({p,onClose}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-label={p.title}><button className="modal-close" onClick={onClose} aria-label="إغلاق">×</button><div className="modal-top"><span className="card-label">{p.label}</span><h2>{p.title}</h2><p>{p.desc}</p><span className="modal-meta">{p.meta}</span></div>{p.type==='interactive'?<iframe title={p.title} src={media+p.src}/>:p.type==='video'?<video controls poster={media+p.poster} src={media+p.video}/>:<img className="modal-image" src={media+p.poster} alt={p.title}/>}<div className="modal-bottom"><span>من حقيبة أعمال تمارا</span><button onClick={onClose}>العودة إلى المشاريع <Arrow/></button></div></div></div>}

createRoot(document.getElementById('root')).render(<App />);
