import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const media = import.meta.env.BASE_URL + 'media/';
const repo = 'https://github.com/tamara126enad/Tamara-Portfolio-Website';

const projects = [
  { id:'barista', type:'interactive', label:'تجربة تفاعلية', title:'كن باريستا', subtitle:'تجربة تدريبية للقهوة والموهيتو', desc:'تجربة متسلسلة تحاكي وردية باريستا: استلام الطلبات، اختيار المكونات، تحضير المشروب، فن اللاتيه، ثم موقف خدمة حقيقي.', meta:'مؤسسة التدريب المهني · إعداد وفكرة: تمارا الشباطات', src:'barista.html', accent:'coral', icon:'☕' },
  { id:'computer', type:'interactive', label:'تجربة تفاعلية', title:'Computer from 1999', subtitle:'حاسوب من عام 1999', desc:'تجربة نوستالجية تعيد واجهة Windows 98 إلى الحياة مع ملفات وألعاب وتفاصيل صغيرة قابلة للاستكشاف.', meta:'تجربة تفاعلية · Tamara’s Portfolio', src:'computer-1999.html', accent:'blue', icon:'▣' },
  { id:'ohm', type:'interactive', label:'مختبر تعليمي', title:'مختبر قانون أوم', subtitle:'الكهرباء بطريقة مرئية', desc:'مختبر تفاعلي يشرح العلاقة بين الجهد والمقاومة وشدة التيار عبر دائرة كهربائية حيّة ولوحة تحكم بالمتغيرات.', meta:'مختبر الفيزياء الكهربائية التفاعلي', src:'ohm-lab.html', accent:'aqua', icon:'⚡' },
  { id:'maze', type:'interactive', label:'لعبة تفاعلية', title:'Maze Runner', subtitle:'5 مراحل من الحماس', desc:'لعبة متاهة بخمس مراحل، عملات، وحوش، بوابة خروج، مؤقت، أرواح ونظام نقاط.', meta:'5 مراحل · Collect · Avoid · Escape', src:'maze-runner.html', accent:'purple', icon:'🌀' },
  { id:'interview-coach', type:'external', label:'مشروع مباشر', title:'Interview Coach', subtitle:'مدرب المقابلات الذكي', desc:'منصة ذكية لتطوير المسيرة المهنية: تحليل السيرة الذاتية، التدريب على مقابلات العمل، ونصائح تساعد على تقديم الذات بثقة.', meta:'مشروع مباشر · تمارا الشباطات', poster:'interview-coach-preview.webp', url:'https://tamara126enad.github.io/interview-coach/', accent:'blue', icon:'◎' },
  { id:'kobo', type:'external', label:'نموذج رقمي', title:'KoboToolbox', subtitle:'نموذج Enketo تفاعلي', desc:'نموذج رقمي مستضاف عبر KoboToolbox. يظهر هنا Preview بصري ثابت لأن بيئة Enketo الخارجية تمنع التضمين المستقر.', meta:'KoboToolbox · Enketo Express', url:'https://ee.kobotoolbox.org/x/11PJXge', accent:'aqua', icon:'⌁' },
  { id:'aqaba', type:'visual', label:'صورة مولدة بالـ AI', title:'Aqaba 2050', subtitle:'زوار العقبة يستكشفون البحر', desc:'مشاهد بصرية مستقبلية مستوحاة من العقبة والبحر، ضمن مجموعة الصور المولدة بالذكاء الاصطناعي.', meta:'صور مولدة بالذكاء الاصطناعي', poster:'aqaba-visitors-web.jpg', gallery:['aqaba-visitors-web.jpg','aqaba-visitors.jpeg','aqaba-whale.jpg'], accent:'blue', icon:'✦' },
  { id:'digital', type:'visual', label:'مهارات رقمية', title:'Digital tools', subtitle:'أدوات رقمية للمهام اليومية', desc:'مادة بصرية ضمن مسار تعلم المهارات الرقمية، تعرض أدوات رقمية للمهام اليومية في المنطقة.', meta:'تعلم مهارات رقمية', poster:'digital-tools-web.jpg', gallery:['digital-tools-web.jpg','digital-tools.png'], accent:'lime', icon:'✺' },
  { id:'creative', type:'visual', label:'أعمال إبداعية', title:'Visual experiments', subtitle:'إعلانات، بطاقات، خرائط وأفكار مصورة', desc:'مجموعة من الأعمال البصرية الأصلية من حقيبة تمارا، مع انتقالات بين الإعلان والتصميم والخرائط التعليمية.', meta:'صور مولدة وتصاميم بصرية', poster:'facebook-ad-web.jpg', gallery:['facebook-ad-web.jpg','cards-web.jpg','carpenter-web.jpg','crochet-map-web.jpg'], accent:'coral', icon:'✷' },
  { id:'anatomy', type:'education', label:'محتوى تعليمي', title:'Human Anatomy', subtitle:'رحلة بصرية عبر جسم الإنسان', desc:'عرض تعليمي بصري من 14 شريحة، من الخلية الواحدة إلى الأجهزة المتكاملة التي تبقي الإنسان على قيد الحياة.', meta:'إعداد: قسم التشريح الطبي · 2026', poster:'tamara-aqaba-web.jpg', accent:'purple', icon:'◌' },
  { id:'safety', type:'video', label:'فيديو معدّل', title:'Child Safety Monitor', subtitle:'قصة قصيرة عن الطمأنينة', desc:'سلسلة فيديوهات معدّلة تبدأ بالتشويق وتنتهي بلحظة راحة أم بعد اكتشاف جهاز مراقبة الطفل.', meta:'فيديوهات معدّلة من حقيبة الأعمال', poster:'child-safety-teaser.jpg', video:'child-safety-teaser.mp4', gallery:['child-safety-teaser.mp4','monitor-reveal.mp4','toddler-story.mp4'], accent:'coral', icon:'◉' },
];

const videos = [
  { title:'Child Safety Monitor', subtitle:'قصة قصيرة عن الطمأنينة', poster:'child-safety-teaser.jpg', video:'child-safety-teaser.mp4', accent:'coral' },
  { title:'Monitor reveal & mother’s relief', subtitle:'لحظة الكشف والراحة', poster:'monitor-reveal.jpg', video:'monitor-reveal.mp4', accent:'blue' },
  { title:'Toddler finds a photograph', subtitle:'قصة بصرية في غرفة النوم', poster:'toddler-story.jpg', video:'toddler-story.mp4', accent:'purple' },
  { title:'Aqaba whale', subtitle:'مشهد متحرك من العقبة', poster:'aqaba-whale.jpg', video:'aqaba-whale.mp4', accent:'aqua' },
  { title:'Thank you, trainer', subtitle:'رسالة تقدير مصورة', poster:'trainer-thanks.jpg', video:'trainer-thanks.mp4', accent:'lime' },
];

const skills = ['تصميم تجارب تفاعلية','المحتوى التعليمي البصري','تحرير الفيديو','الصور المولّدة بالذكاء الاصطناعي','التجارب القصصية','التصميم الرقمي'];
const nav = [['about','عن تمارا'],['skills','المهارات'],['projects','المشاريع'],['videos','الفيديو'],['creative','أعمال إبداعية'],['contact','تواصل']];

function Arrow(){ return <span className="arrow" aria-hidden="true">↗</span> }
function SectionKicker({children,n}){ return <div className="section-kicker"><span>{n}</span><i></i><b>{children}</b></div> }
function SafeImage({src,alt,className='',...props}){ const [failed,setFailed]=useState(false); return failed?<div className={'image-fallback '+className}><span>✦</span><small>{alt}</small></div>:<img className={className} src={media+src} alt={alt} onError={()=>setFailed(true)} {...props}/> }

function App(){
 const [menu,setMenu]=useState(false); const [filter,setFilter]=useState('all'); const [active,setActive]=useState(null);
 const filtered=useMemo(()=>filter==='all'?projects:projects.filter(p=>p.type===filter),[filter]);
 useEffect(()=>{document.body.style.overflow=active?'hidden':''; return()=>document.body.style.overflow=''},[active]);
 const go=id=>{setMenu(false); document.getElementById(id)?.scrollIntoView({behavior:'smooth'});};
 return <>
  <header className="topbar"><a className="brand" href="#top" onClick={()=>go('top')}><span className="brand-mark">ت</span><span>تمارا<small>حقيبة أعمال رقمية</small></span></a><nav className={menu?'nav open':'nav'}>{nav.map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<a className="nav-cta" href="#projects" onClick={()=>setMenu(false)}>استكشف الأعمال <Arrow/></a></nav><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="فتح القائمة">{menu?'×':'☰'}</button></header>
  <main id="top">
   <section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="pulse"></span> معرض رقمي حيّ من أعمال تمارا</div><h1>أفكار<br/><em>تتحرك</em><br/>وتُعاش.</h1><p className="hero-lead">تمارا الشباطات — أصمم تجارب رقمية، محتوى تعليمي، وصورًا وفيديوهات تحمل فكرة واضحة وتترك أثرًا.</p><div className="hero-actions"><a className="button primary" href="#projects">استكشف الأعمال <Arrow/></a><a className="text-link" href="#videos">شاهد الفيديو <Arrow/></a></div></div><div className="hero-art"><div className="hero-orbit orbit-a"></div><div className="hero-orbit orbit-b"></div><div className="hero-tile tile-back"><SafeImage src="cards-web.jpg" alt="بطاقات مولدة"/></div><div className="hero-tile tile-main"><SafeImage src="tamara-aqaba-web.jpg" alt="عمل بصري من حقيبة أعمال تمارا" fetchPriority="high"/><span>01 / 10</span></div><div className="hero-tile tile-front"><SafeImage src="digital-tools-web.jpg" alt="مهارات رقمية"/></div><div className="stamp">DIGITAL<br/>EXHIBITION<br/><span>✦</span></div></div><div className="scroll-cue"><span>اسحب للاستكشاف</span><i></i></div></section>
   <section id="about" className="about shell"><SectionKicker n="01">عن تمارا</SectionKicker><div className="about-grid"><h2>حين تصبح التقنية<br/><span>مساحة للخيال.</span></h2><div><p className="large-copy">أبني أعمالًا تجمع بين الفكرة، الصورة، والتفاعل. في حقيبتي تجارب تعليمية وألعاب ومختبرات رقمية، إلى جانب فيديوهات وصور مولّدة بالذكاء الاصطناعي.</p><p className="muted">من تجربة «كن باريستا» التدريبية إلى مختبر قانون أوم ومتاهة بخمس مراحل — كل مشروع يبدأ بسؤال: كيف نجعل المعرفة أو القصة أكثر قابلية للّمس؟</p><a className="text-link" href="#projects">شاهد المعرض <Arrow/></a></div></div></section>
   <section id="skills" className="skills shell"><SectionKicker n="02">ما أفعله</SectionKicker><div className="skills-grid"><h2>مساحات<br/><em>أتحرك بينها.</em></h2><div className="skill-list">{skills.map((s,i)=><div className="skill" key={s}><span>0{i+1}</span><b>{s}</b><Arrow/></div>)}</div></div></section>
   <section id="projects" className="projects shell"><div className="projects-head"><div><SectionKicker n="03">المعرض الرئيسي</SectionKicker><h2>أعمال حقيقية،<br/><em>تجارب قابلة للّمس.</em></h2></div><p>المشاريع هنا ليست أسماء فقط؛ كل بطاقة تفتح العمل نفسه أو معاينة بصرية حقيقية من حقيبة أعمال تمارا.</p></div><div className="filters">{[['all','الكل'],['interactive','تفاعلي'],['external','مباشر'],['video','فيديو'],['visual','بصري'],['education','تعليمي']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label} <sup>{id==='all'?projects.length:projects.filter(p=>p.type===id).length}</sup></button>)}</div><div className="project-grid">{filtered.map((p,i)=><ProjectCard key={p.id} p={p} i={i} onOpen={()=>setActive(p)}/>)}</div></section>
   <section id="videos" className="video-section"><div className="shell"><SectionKicker n="04">الفيديوهات</SectionKicker><div className="video-heading"><h2>الصورة حين<br/><em>تبدأ بالحركة.</em></h2><p>مختارات من الفيديوهات المعدلة الموجودة في حقيبة الأعمال، مع تشغيل مباشر وملء الشاشة.</p></div><div className="video-grid">{videos.map((v,i)=><VideoCard key={v.video} v={v} i={i} onOpen={()=>setActive({...v,type:'video',label:'فيديو معدّل',desc:v.subtitle,meta:'فيديو من حقيبة أعمال تمارا'})}/>)}</div></div></section>
   <section id="creative" className="creative shell"><div className="creative-head"><SectionKicker n="05">الأعمال الإبداعية</SectionKicker><h2>ألوان كثيرة،<br/><em>فكرة واحدة.</em></h2><p>إعلانات، بطاقات، خرائط، صور مولدة، ومواد تعلم رقمية — معرض بصري يتغير مع كل مشروع.</p></div><div className="creative-gallery">{['facebook-ad-web.jpg','cards-web.jpg','carpenter-web.jpg','crochet-map-web.jpg','aqaba-visitors-web.jpg'].map((src,i)=><button key={src} className={'gallery-tile gallery-'+i} onClick={()=>setActive({type:'visual',label:'عمل إبداعي',title:'Visual experiment',desc:'عمل بصري من حقيبة أعمال تمارا.',meta:'صور وتصاميم أصلية',poster:src,gallery:['facebook-ad-web.jpg','cards-web.jpg','carpenter-web.jpg','crochet-map-web.jpg','aqaba-visitors-web.jpg'],accent:'coral'})}><SafeImage src={src} alt="عمل إبداعي من حقيبة الأعمال" loading="lazy"/><span>عرض العمل <Arrow/></span></button>)}</div></section>
   <section id="experience" className="experience shell"><SectionKicker n="06">الخبرة كما تظهر في الأعمال</SectionKicker><div className="timeline"><div className="timeline-item"><span className="year">01</span><div><h3>مؤسسة التدريب المهني</h3><p>برنامج التدريب الفندقي — تجربة «كن باريستا» التفاعلية، إعداد وفكرة: تمارا الشباطات.</p></div><b>تجربة رقمية</b></div><div className="timeline-item"><span className="year">02</span><div><h3>التعلم الرقمي</h3><p>مسار «تعلم مهارات رقمية» مع مادة بصرية عن الأدوات الرقمية والمهام اليومية.</p></div><b>محتوى بصري</b></div><div className="timeline-item"><span className="year">03</span><div><h3>التعليم والتجريب</h3><p>مختبر قانون أوم، عرض علم التشريح البشري، وتجارب تفاعلية تجعل المعلومة قابلة للاستكشاف.</p></div><b>تعليم تفاعلي</b></div></div></section>
   <section className="archive shell"><SectionKicker n="07">أرشيف العمل</SectionKicker><div className="archive-grid"><div><h2>المحتوى الأصلي<br/><em>بقي محفوظًا.</em></h2><p className="muted">تم نقل محتوى Google Drive إلى GitHub بنفس المجلدات والأسماء العربية، بما في ذلك التجارب التفاعلية، الفيديوهات، الصور، المسارات الصوتية، وملفات العرض.</p><a className="button secondary" href={repo} target="_blank" rel="noreferrer">فتح المستودع <Arrow/></a></div><div className="archive-list"><span>تجارب تفاعلية</span><span>صور مولدة بالذكاء الاصطناعي</span><span>فيديوهات معدلة</span><span>مسارات صوتية</span><span>قصص أطفال ومواد تعليمية</span></div></div></section>
   <section id="contact" className="contact shell"><SectionKicker n="08">لنبقى على تواصل</SectionKicker><div className="contact-inner"><h2>لديك فكرة؟<br/><em>لنعطها شكلًا.</em></h2><a className="contact-email" href={repo} target="_blank" rel="noreferrer">افتحي المعرض على GitHub <Arrow/></a><div className="contact-foot"><span>حقيبة أعمال تمارا · 2026</span><span>صُنع بشغف وفضول</span></div></div></section>
  </main><footer><span>© 2026 تمارا الشباطات</span><a href="#top">إلى الأعلى ↑</a></footer>{active&&<ProjectModal p={active} onClose={()=>setActive(null)}/>}</>
}

function ProjectCard({p,i,onOpen}){return <article className={'project-card '+p.accent} style={{'--delay':`${i*45}ms`}} onClick={onOpen} tabIndex="0" onKeyDown={e=>e.key==='Enter'&&onOpen()}><div className={'card-media '+(p.type==='external'?'external-media':'')}>{p.poster?<SafeImage src={p.poster} alt={p.title} loading="lazy"/>:<div className="abstract"><span>{p.icon}</span><small>{p.type==='interactive'?'LIVE EXPERIENCE':'DIGITAL WORK'}</small></div>}<div className="card-shade"></div><span className="card-open">↗</span>{p.type==='interactive'&&<span className="live-dot">تجربة حيّة</span>}{p.type==='external'&&<span className="live-dot">يفتح خارجيًا</span>}{p.type==='video'&&<span className="play-dot">▶</span>}</div><div className="card-body"><div><span className="card-label">{p.label}</span><h3>{p.title}</h3><p>{p.subtitle}</p>{p.url&&<a className="open-project" href={p.url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Open Project <Arrow/></a>}</div><span className="card-no">{String(i+1).padStart(2,'0')}</span></div></article>}
function VideoCard({v,i,onOpen}){return <button className={'video-card '+v.accent} onClick={onOpen}><div className="video-poster"><SafeImage src={v.poster} alt={v.title} loading="lazy"/><span className="play-button">▶</span><span className="video-index">0{i+1}</span></div><span className="video-copy"><b>{v.title}</b><small>{v.subtitle}</small></span></button>}
function ProjectModal({p,onClose}){const gallery=p.gallery?.length?p.gallery:(p.poster?[p.poster]:[]);const [index,setIndex]=useState(0);const current=gallery[index];useEffect(()=>{const onKey=e=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')setIndex(i=>(i+1)%Math.max(gallery.length,1));if(e.key==='ArrowLeft')setIndex(i=>(i-1+Math.max(gallery.length,1))%Math.max(gallery.length,1));};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[gallery.length,onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal" role="dialog" aria-modal="true" aria-label={p.title||p.label}><button className="modal-close" onClick={onClose} aria-label="إغلاق">×</button><div className="modal-top"><span className="card-label">{p.label}</span><h2>{p.title}</h2><p>{p.desc}</p><span className="modal-meta">{p.meta}</span>{p.url&&<a className="button primary external-button" href={p.url} target="_blank" rel="noreferrer">Open Live Project <Arrow/></a>}</div>{p.type==='interactive'?<iframe title={p.title} src={media+p.src}/>:p.type==='video'?<video controls autoPlay poster={media+p.poster} src={media+p.video}/>:p.type==='external'&&!p.poster?<div className="external-placeholder"><strong>KoboToolbox</strong><span>Enketo Express · افتح المشروع في تبويب جديد</span></div>:current?<SafeImage className="modal-image" src={current} alt={p.title} />:<div className="external-placeholder"><strong>Digital Work</strong><span>Preview غير متاح، افتح الأرشيف لمشاهدة المصدر</span></div>}{gallery.length>1&&<div className="gallery-controls"><button onClick={()=>setIndex(i=>(i-1+gallery.length)%gallery.length)}>السابق</button><span>{index+1} / {gallery.length}</span><button onClick={()=>setIndex(i=>(i+1)%gallery.length)}>التالي</button></div>}<div className="modal-bottom"><span>من حقيبة أعمال تمارا</span><button onClick={onClose}>العودة إلى المعرض <Arrow/></button></div></div></div>}

class SafeApp extends React.Component { state={failed:false}; static getDerivedStateFromError(){return {failed:true}}; render(){return this.state.failed?<div className="fatal-fallback"><h1>المعرض سيعود قريبًا</h1><p>تعذر تحميل جزء من المعرض. افتحي الملفات الأصلية من GitHub.</p><a className="button primary" href={repo}>فتح GitHub <Arrow/></a></div>:this.props.children} }
createRoot(document.getElementById('root')).render(<SafeApp><App/></SafeApp>);
